services:
  backend:
    image: task-manager-backend
    build:
      context: ./task_manager_server
      dockerfile: Dockerfile  
    container_name: task-manager-backend
    volumes:      
      # - ./backend:/app  # production
      - ./task_manager_server:/task_manager_server  # for local development
      # TODO: create volume for the static files
    ports:
      - "8000:8000"
      